### PR TITLE
brave: adds PROTO3 encoding

### LINKED ISSUE #178: Support proto in AsyncZipkinSpanHandler
Right now, it is required to use JSON when using brave's direct encoder.

```
Caused by: java.lang.IllegalArgumentException: Encoder doesn't match Sender: JSON PROTO3
	at zipkin2.reporter.AsyncReporter$Builder.build(AsyncReporter.java:201)
	at zipkin2.reporter.brave.AsyncZipkinSpanHandler.<init>(AsyncZipkinSpanHandler.java:152)
	at zipkin2.reporter.brave.AsyncZipkinSpanHandler$Builder.build(AsyncZipkinSpanHandler.java:147)
	at zipkin2.server.internal.brave.ZipkinSelfTracingConfiguration.reporter(ZipkinSelfTracingConfiguration.java:64)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 140 more
```

### PR DESCRIPTION
**Pull request by codefromthecrypt**
This adds `MutableSpanEncoder.PROTO3` similar to what's available for `zipkin2.Span`. The code and tests are based on similar inside zipkin and brave. This is added to the reporter, not brave, to reduce version lock-up for a useful, but more rare encoding type.
```
Benchmark                                                                               Mode     Cnt     Score     Error   Units
MutableSpanBytesEncoderBenchmarks.encode_bigClientSpan_json:gc.alloc.rate.norm        sample      15  584.183 ± 0.045    B/op
MutableSpanBytesEncoderBenchmarks.encode_bigClientSpan_json:p0.99                     sample            1.166           us/op
MutableSpanBytesEncoderBenchmarks.encode_bigClientSpan_proto:gc.alloc.rate.norm       sample      15  472.141 ± 0.006    B/op
MutableSpanBytesEncoderBenchmarks.encode_bigClientSpan_proto:p0.99                    sample            1.042           us/op
MutableSpanBytesEncoderBenchmarks.encode_serverSpan_json:gc.alloc.rate.norm           sample      15  288.054 ± 0.008    B/op
MutableSpanBytesEncoderBenchmarks.encode_serverSpan_json:p0.99                        sample            0.417           us/op
MutableSpanBytesEncoderBenchmarks.encode_serverSpan_proto:gc.alloc.rate.norm          sample      15  200.052 ± 0.006    B/op
MutableSpanBytesEncoderBenchmarks.encode_serverSpan_proto:p0.99                       sample            0.417           us/op
MutableSpanBytesEncoderBenchmarks.sizeInBytes_bigClientSpan_json:gc.alloc.rate.norm   sample      15    0.043 ± 0.011    B/op
MutableSpanBytesEncoderBenchmarks.sizeInBytes_bigClientSpan_json:p0.99                sample            0.334           us/op
MutableSpanBytesEncoderBenchmarks.sizeInBytes_bigClientSpan_proto:gc.alloc.rate.norm  sample      15    0.028 ± 0.004    B/op
MutableSpanBytesEncoderBenchmarks.sizeInBytes_bigClientSpan_proto:p0.99               sample            0.250           us/op
MutableSpanBytesEncoderBenchmarks.sizeInBytes_serverSpan_json:gc.alloc.rate.norm      sample      15    0.013 ± 0.002    B/op
MutableSpanBytesEncoderBenchmarks.sizeInBytes_serverSpan_json:p0.99                   sample            0.125           us/op
MutableSpanBytesEncoderBenchmarks.sizeInBytes_serverSpan_proto:gc.alloc.rate.norm     sample      15    0.008 ± 0.001    B/op
MutableSpanBytesEncoderBenchmarks.sizeInBytes_serverSpan_proto:p0.99                  sample            0.125           us/op
```

Fixes #178

### CODE REVIEW

File: brave/src/test/java/zipkin2/reporter/brave/JsonV2RoundTripTest.java [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+import org.junit.jupiter.api.Test;
+import zipkin2.codec.SpanBytesDecoder;
+
+class JsonV2RoundTripTest extends RoundTripTest {
+  JsonV2RoundTripTest() {
+    super(MutableSpanBytesEncoder.JSON_V2, SpanBytesDecoder.JSON_V2);
+  }
+
+  @Override @Disabled @Test void differentErrorTagName() {
+    // awaiting https://github.com/openzipkin/brave/pull/1415 to be released
```
Comment (codefromthecrypt) [inline brave/src/test/java/zipkin2/reporter/brave/JsonV2RoundTripTest.java:26]: once this merges I'll cut brave 6.0.1 and that should scrub out this disabled thingy

**Comment by codefromthecrypt** [comment]
This adds 24KB to the brave jar, which I think is not enough for people to fuss about.

**Comment by codefromthecrypt** [comment]
Note: write speed is less than json, which might not seem intuitive. However, there is some work to do converting string IPs to their binary representation. Similarly, we need to decode the hex IDs. So, if you were expecting dramatically different encoding speed, bear this in mind. It is in the same ballpark as JSON even if on the wire will be smaller and of course other advantages of proto. I'll post benchmarks in a few minutes when they complete.

**Comment by codefromthecrypt** [comment]
actually I got found the biggest issue and now proto is faster. Someone who wants to mess around and improve the ipv6 writer more, but anyway encoding is off-thread. The most important latency is sizeOfBytes which is a guard to make sure a span isn't too big to send. This is faster in proto a lot. Anyway updated desc.

**Comment by codefromthecrypt** [comment]
updating the ipv6 writing code to latest guava (as the previous snippet copied allocated a lot..) did the trick. proto is now as fast or faster than json as one might expect.

@anuraaga I'm done mucking around if you have time for a look. only other thing I'll do here is bump to brave 6.0.1 which is releasing now.

**Review by anuraaga — APPROVED** [review]

**Comment by codefromthecrypt** [comment]
thanks for all the reviews, @anuraaga! I'll do a quick test with micrometer+spring boot prior to cutting the release.
